name: carbon-intensity-import-ci
run-name: Run ${{ github.run_id }}
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s tests -t tests
