name: carbon-intensity-import-ci
run-name: Pipeline ${{ github.event_name }} ${{ github.ref_name }}
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up app environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: '3.10'
          environment-file: environment.yml
      - name: Run tests
        run: python -m unittest discover -s tests -t tests
