name: Run
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: go build
      - name: Run importer
        run: ./carbon-intensity-importer
      - name: Archive produced CSV
        uses: actions/upload-artifact@v3
        with:
          name: output-csv
          path: out.csv
