name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: go build